"""add v2 general catalog shadow schema

Revision ID: 0aafbcfc19d5
Revises: 6f2a91d4c8b7
Create Date: 2026-08-21 10:39:54.489493
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0aafbcfc19d5"
down_revision: str | None = "6f2a91d4c8b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v2_brand",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','UNKNOWN')", name=op.f("ck_v2_brand_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_brand")),
        sa.UniqueConstraint("code", name=op.f("uq_v2_brand_code")),
    )
    op.create_table(
        "v2_category",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("parent_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=True),
        sa.Column("level", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("is_leaf", sa.Boolean(), nullable=False),
        sa.Column("default_measure_type", sa.String(length=16), nullable=True),
        sa.Column("attribute_profile_code", sa.String(length=64), nullable=False),
        sa.Column("attribute_profile_version", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_measure_type IS NULL OR "
            "default_measure_type IN ('WEIGHT','VOLUME','COUNT','LENGTH','AREA','SET','OTHER')",
            name=op.f("ck_v2_category_default_measure_type"),
        ),
        sa.CheckConstraint("level >= 0", name=op.f("ck_v2_category_level")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["v2_category.id"],
            name=op.f("fk_v2_category_parent_id_v2_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_category")),
        sa.UniqueConstraint("code", name=op.f("uq_v2_category_code")),
    )
    op.create_index("ix_v2_category_enabled", "v2_category", ["enabled"], unique=False)
    op.create_index("ix_v2_category_parent_id", "v2_category", ["parent_id"], unique=False)
    op.create_index("ix_v2_category_path", "v2_category", ["path"], unique=False)
    op.create_table(
        "v2_source_channel",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("business_mode", sa.String(length=24), nullable=False),
        sa.Column("access_mode", sa.String(length=16), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("allowed_domains", sa.JSON(), nullable=False),
        sa.Column("region_mode", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'CNY'"), nullable=False),
        sa.Column("connector_code", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "access_mode IN ('API','HTTP','BROWSER','FILE','MIXED')",
            name=op.f("ck_v2_source_channel_access_mode"),
        ),
        sa.CheckConstraint(
            "business_mode IN ('SELF_OPERATED','MARKETPLACE','HYBRID','WHOLESALE')",
            name=op.f("ck_v2_source_channel_business_mode"),
        ),
        sa.CheckConstraint("currency = 'CNY'", name=op.f("ck_v2_source_channel_currency")),
        sa.CheckConstraint(
            "region_mode IN ('NATIONAL','REGIONAL','MIXED')",
            name=op.f("ck_v2_source_channel_region_mode"),
        ),
        sa.CheckConstraint(
            "source_type IN "
            "('OFFICIAL_MALL','MAJOR_ECOMMERCE','SUPERMARKET','PERSONAL_SITE','PUBLIC_DATA')",
            name=op.f("ck_v2_source_channel_source_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_source_channel")),
        sa.UniqueConstraint("code", name=op.f("uq_v2_source_channel_code")),
    )
    op.create_table(
        "v2_catalog_item",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("brand_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("item_type", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("series_name", sa.String(length=128), nullable=True),
        sa.Column("model_number", sa.String(length=128), nullable=True),
        sa.Column("base_attributes", sa.JSON(), nullable=False),
        sa.Column("record_origin", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('MODEL','COMMODITY','GENERIC_GOOD')",
            name=op.f("ck_v2_catalog_item_item_type"),
        ),
        sa.CheckConstraint(
            "record_origin IN ('MANUAL','RULE','IMPORT','AUTO')",
            name=op.f("ck_v2_catalog_item_record_origin"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','REVIEW_REQUIRED','SUPERSEDED')",
            name=op.f("ck_v2_catalog_item_status"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["v2_brand.id"],
            name=op.f("fk_v2_catalog_item_brand_id_v2_brand"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["v2_category.id"],
            name=op.f("fk_v2_catalog_item_category_id_v2_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_catalog_item")),
        sa.UniqueConstraint("canonical_key", name=op.f("uq_v2_catalog_item_canonical_key")),
    )
    op.create_index("ix_v2_catalog_item_brand_id", "v2_catalog_item", ["brand_id"], unique=False)
    op.create_index(
        "ix_v2_catalog_item_category_status",
        "v2_catalog_item",
        ["category_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_v2_catalog_item_model_number", "v2_catalog_item", ["model_number"], unique=False
    )
    op.create_table(
        "v2_crawl_run",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("source_channel_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("region_scope", sa.String(length=24), nullable=False),
        sa.Column("region_code", sa.String(length=32), nullable=False),
        sa.Column("category_scope", sa.JSON(), nullable=False),
        sa.Column("run_type", sa.String(length=24), nullable=False),
        sa.Column("trigger_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("adapter_version", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "discovered_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "fetched_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "accepted_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "review_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "rejected_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "failed_count",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("error_summary", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "region_scope IN "
            "('NATIONAL','PROVINCE','CITY','DISTRICT','DELIVERY_ZONE','UNKNOWN','MULTI')",
            name=op.f("ck_v2_crawl_run_region_scope"),
        ),
        sa.CheckConstraint(
            "run_type IN ('DISCOVERY','PRICE','FULL','REPLAY')",
            name=op.f("ck_v2_crawl_run_run_type"),
        ),
        sa.CheckConstraint(
            "status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED')",
            name=op.f("ck_v2_crawl_run_status"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_v2_crawl_run_time_range"),
        ),
        sa.CheckConstraint(
            "(region_scope <> 'NATIONAL' OR region_code = 'CN') AND "
            "(region_scope <> 'MULTI' OR region_code = '*')",
            name=op.f("ck_v2_crawl_run_region_semantics"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('SCHEDULED','MANUAL','QUERY_RECRAWL')",
            name=op.f("ck_v2_crawl_run_trigger_type"),
        ),
        sa.CheckConstraint(
            "discovered_count >= 0 AND fetched_count >= 0 AND accepted_count >= 0 "
            "AND review_count >= 0 AND rejected_count >= 0 AND failed_count >= 0",
            name=op.f("ck_v2_crawl_run_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_channel_id"],
            ["v2_source_channel.id"],
            name=op.f("fk_v2_crawl_run_source_channel_id_v2_source_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_crawl_run")),
    )
    op.create_index(
        "ix_v2_crawl_run_channel_started",
        "v2_crawl_run",
        ["source_channel_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_crawl_run_region_started",
        "v2_crawl_run",
        ["region_code", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_crawl_run_status_started", "v2_crawl_run", ["status", "started_at"], unique=False
    )
    op.create_table(
        "v2_merchant",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("source_channel_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("merchant_key_hash", sa.String(length=64), nullable=False),
        sa.Column("external_merchant_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("seller_type", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("first_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "seller_type IN "
            "('PLATFORM_SELF','BRAND_OFFICIAL','THIRD_PARTY','INDIVIDUAL',"
            "'PUBLIC_MARKET','UNKNOWN')",
            name=op.f("ck_v2_merchant_seller_type"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','UNKNOWN')", name=op.f("ck_v2_merchant_status")
        ),
        sa.CheckConstraint(
            "verification_status IN ('VERIFIED','UNVERIFIED','UNKNOWN')",
            name=op.f("ck_v2_merchant_verification_status"),
        ),
        sa.CheckConstraint(
            "last_seen_at >= first_seen_at",
            name=op.f("ck_v2_merchant_observation_range"),
        ),
        sa.ForeignKeyConstraint(
            ["source_channel_id"],
            ["v2_source_channel.id"],
            name=op.f("fk_v2_merchant_source_channel_id_v2_source_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_merchant")),
        sa.UniqueConstraint(
            "source_channel_id", "merchant_key_hash", name="uq_v2_merchant_channel_key"
        ),
    )
    op.create_index(
        "ix_v2_merchant_channel_external",
        "v2_merchant",
        ["source_channel_id", "external_merchant_id"],
        unique=False,
    )
    op.create_index("ix_v2_merchant_seller_type", "v2_merchant", ["seller_type"], unique=False)
    op.create_table(
        "v2_item_variant",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("catalog_item_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("supersedes_variant_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("variant_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gtin", sa.String(length=32), nullable=True),
        sa.Column("manufacturer_part_number", sa.String(length=128), nullable=True),
        sa.Column("condition_code", sa.String(length=24), nullable=False),
        sa.Column("measure_type", sa.String(length=16), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_min", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_max", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("base_unit", sa.String(length=16), nullable=False),
        sa.Column("package_count", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("identity_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition_code IN ('NEW','USED','REFURBISHED','UNKNOWN')",
            name=op.f("ck_v2_item_variant_condition_code"),
        ),
        sa.CheckConstraint(
            "measure_type IN ('WEIGHT','VOLUME','COUNT','LENGTH','AREA','SET','OTHER')",
            name=op.f("ck_v2_item_variant_measure_type"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','REVIEW_REQUIRED','SUPERSEDED')",
            name=op.f("ck_v2_item_variant_status"),
        ),
        sa.CheckConstraint(
            "(quantity_min IS NULL AND quantity_max IS NULL) OR "
            "(quantity_min IS NOT NULL AND quantity_max IS NOT NULL)",
            name=op.f("ck_v2_item_variant_quantity_range_pair"),
        ),
        sa.CheckConstraint(
            "package_count IS NULL OR package_count > 0",
            name=op.f("ck_v2_item_variant_package_count"),
        ),
        sa.CheckConstraint(
            "quantity_max IS NULL OR quantity_max > 0", name=op.f("ck_v2_item_variant_quantity_max")
        ),
        sa.CheckConstraint(
            "quantity_min IS NULL OR quantity_max >= quantity_min",
            name=op.f("ck_v2_item_variant_quantity_range_order"),
        ),
        sa.CheckConstraint(
            "quantity_min IS NULL OR quantity_min > 0", name=op.f("ck_v2_item_variant_quantity_min")
        ),
        sa.CheckConstraint(
            "quantity_value IS NULL OR (quantity_min IS NULL AND quantity_max IS NULL)",
            name=op.f("ck_v2_item_variant_quantity_exact_or_range"),
        ),
        sa.CheckConstraint(
            "quantity_value IS NULL OR quantity_value > 0",
            name=op.f("ck_v2_item_variant_quantity_value"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["v2_catalog_item.id"],
            name=op.f("fk_v2_item_variant_catalog_item_id_v2_catalog_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_variant_id"],
            ["v2_item_variant.id"],
            name=op.f("fk_v2_item_variant_supersedes_variant_id_v2_item_variant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_item_variant")),
        sa.UniqueConstraint("catalog_item_id", "variant_key", name="uq_v2_variant_item_key"),
    )
    op.create_index("ix_v2_item_variant_gtin", "v2_item_variant", ["gtin"], unique=False)
    op.create_index(
        "ix_v2_item_variant_identity", "v2_item_variant", ["identity_fingerprint"], unique=False
    )
    op.create_index(
        "ix_v2_item_variant_mpn", "v2_item_variant", ["manufacturer_part_number"], unique=False
    )
    op.create_table(
        "v2_source_listing",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("source_channel_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("merchant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("listing_key", sa.String(length=512), nullable=False),
        sa.Column("listing_key_hash", sa.String(length=64), nullable=False),
        sa.Column("external_product_id", sa.String(length=128), nullable=True),
        sa.Column("external_sku_id", sa.String(length=128), nullable=True),
        sa.Column("price_nature", sa.String(length=32), nullable=False),
        sa.Column("canonical_url", sa.String(length=1024), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("current_revision_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column(
            "lifecycle_status",
            sa.String(length=24),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column(
            "consecutive_misses",
            mysql.INTEGER(unsigned=True),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("first_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('ACTIVE','INACTIVE','UNKNOWN')",
            name=op.f("ck_v2_source_listing_lifecycle_status"),
        ),
        sa.CheckConstraint(
            "price_nature IN ('RETAIL_OFFER','WHOLESALE_OFFER','RETAIL_AVERAGE',"
            "'WHOLESALE_AVERAGE','MARKET_AVERAGE','UNKNOWN')",
            name=op.f("ck_v2_source_listing_price_nature"),
        ),
        sa.CheckConstraint(
            "consecutive_misses >= 0", name=op.f("ck_v2_source_listing_consecutive_misses")
        ),
        sa.CheckConstraint(
            "last_seen_at >= first_seen_at",
            name=op.f("ck_v2_source_listing_observation_range"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["v2_merchant.id"],
            name=op.f("fk_v2_source_listing_merchant_id_v2_merchant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_channel_id"],
            ["v2_source_channel.id"],
            name=op.f("fk_v2_source_listing_source_channel_id_v2_source_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_source_listing")),
        sa.UniqueConstraint(
            "source_channel_id",
            "merchant_id",
            "listing_key_hash",
            name="uq_v2_listing_channel_merchant_key",
        ),
    )
    op.create_index(
        "ix_v2_listing_channel_external_product",
        "v2_source_listing",
        ["source_channel_id", "external_product_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_listing_channel_external_sku",
        "v2_source_listing",
        ["source_channel_id", "external_sku_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_listing_lifecycle_seen",
        "v2_source_listing",
        ["lifecycle_status", "last_seen_at"],
        unique=False,
    )
    op.create_index("ix_v2_listing_url_hash", "v2_source_listing", ["url_hash"], unique=False)
    op.create_table(
        "v2_crawl_record",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("crawl_run_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("source_listing_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("replayed_from_record_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_key", sa.String(length=255), nullable=False),
        sa.Column("request_url", sa.String(length=1024), nullable=False),
        sa.Column("final_url", sa.String(length=1024), nullable=False),
        sa.Column("fetch_method", sa.String(length=16), nullable=False),
        sa.Column("http_status", mysql.SMALLINT(unsigned=True), nullable=True),
        sa.Column("fetch_status", sa.String(length=24), nullable=False),
        sa.Column("parse_status", sa.String(length=24), nullable=False),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_hash", sa.String(length=64), nullable=True),
        sa.Column("raw_path", sa.String(length=1024), nullable=True),
        sa.Column("artifact_manifest", sa.JSON(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("raw_size_bytes", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("duration_ms", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("fetched_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('CATEGORY','SEARCH','LISTING','SKU','OFFER','PUBLIC_PRICE')",
            name=op.f("ck_v2_crawl_record_entity_type"),
        ),
        sa.CheckConstraint(
            "fetch_method IN ('API','HTTP','BROWSER','FILE','REPLAY')",
            name=op.f("ck_v2_crawl_record_fetch_method"),
        ),
        sa.CheckConstraint(
            "fetch_status IN ('PENDING','SUCCEEDED','SKIPPED','FAILED')",
            name=op.f("ck_v2_crawl_record_fetch_status"),
        ),
        sa.CheckConstraint(
            "parse_status IN ('PENDING','SUCCEEDED','SKIPPED','FAILED')",
            name=op.f("ck_v2_crawl_record_parse_status"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('PENDING','SUCCEEDED','SKIPPED','FAILED')",
            name=op.f("ck_v2_crawl_record_validation_status"),
        ),
        sa.CheckConstraint("duration_ms >= 0", name=op.f("ck_v2_crawl_record_duration")),
        sa.CheckConstraint(
            "http_status IS NULL OR (http_status >= 100 AND http_status <= 599)",
            name=op.f("ck_v2_crawl_record_http_status"),
        ),
        sa.CheckConstraint(
            "raw_size_bytes IS NULL OR raw_size_bytes >= 0",
            name=op.f("ck_v2_crawl_record_raw_size"),
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["v2_crawl_run.id"],
            name=op.f("fk_v2_crawl_record_crawl_run_id_v2_crawl_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replayed_from_record_id"],
            ["v2_crawl_record.id"],
            name=op.f("fk_v2_crawl_record_replayed_from_record_id_v2_crawl_record"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["v2_source_listing.id"],
            name=op.f("fk_v2_crawl_record_source_listing_id_v2_source_listing"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_crawl_record")),
    )
    op.create_index(
        "ix_v2_crawl_record_entity", "v2_crawl_record", ["entity_type", "entity_key"], unique=False
    )
    op.create_index(
        "ix_v2_crawl_record_fetched_at", "v2_crawl_record", ["fetched_at"], unique=False
    )
    op.create_index(
        "ix_v2_crawl_record_listing_fetched",
        "v2_crawl_record",
        ["source_listing_id", "fetched_at"],
        unique=False,
    )
    op.create_index("ix_v2_crawl_record_raw_hash", "v2_crawl_record", ["raw_hash"], unique=False)
    op.create_index(
        "ix_v2_crawl_record_run_parse",
        "v2_crawl_record",
        ["crawl_run_id", "parse_status"],
        unique=False,
    )
    op.create_table(
        "v2_listing_revision",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("source_listing_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("first_crawl_record_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("revision_no", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("source_title", sa.String(length=512), nullable=False),
        sa.Column("source_category_path", sa.String(length=512), nullable=True),
        sa.Column("source_attributes", sa.JSON(), nullable=False),
        sa.Column("normalized_attributes", sa.JSON(), nullable=False),
        sa.Column("condition_code", sa.String(length=24), nullable=False),
        sa.Column("measure_type", sa.String(length=16), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_min", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_max", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_unit", sa.String(length=16), nullable=True),
        sa.Column("base_quantity_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("base_quantity_min", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("base_quantity_max", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("base_unit", sa.String(length=16), nullable=True),
        sa.Column("package_count", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("identity_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("normalizer_version", sa.String(length=64), nullable=False),
        sa.Column("quality_status", sa.String(length=24), nullable=False),
        sa.Column("rejection_code", sa.String(length=64), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("first_observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(quality_status = 'ACCEPTED' AND rejection_code IS NULL) OR "
            "(quality_status <> 'ACCEPTED' AND rejection_code IS NOT NULL)",
            name=op.f("ck_v2_listing_revision_quality_semantics"),
        ),
        sa.CheckConstraint(
            "condition_code IN ('NEW','USED','REFURBISHED','UNKNOWN')",
            name=op.f("ck_v2_listing_revision_condition_code"),
        ),
        sa.CheckConstraint(
            "measure_type IN ('WEIGHT','VOLUME','COUNT','LENGTH','AREA','SET','OTHER')",
            name=op.f("ck_v2_listing_revision_measure_type"),
        ),
        sa.CheckConstraint(
            "quality_status IN ('ACCEPTED','REVIEW_REQUIRED','REJECTED')",
            name=op.f("ck_v2_listing_revision_quality_status"),
        ),
        sa.CheckConstraint(
            "revision_no > 0",
            name=op.f("ck_v2_listing_revision_revision_no"),
        ),
        sa.CheckConstraint(
            "(base_quantity_min IS NULL AND base_quantity_max IS NULL) OR "
            "(base_quantity_min IS NOT NULL AND base_quantity_max IS NOT NULL)",
            name=op.f("ck_v2_listing_revision_base_quantity_range_pair"),
        ),
        sa.CheckConstraint(
            "(quantity_min IS NULL AND quantity_max IS NULL) OR "
            "(quantity_min IS NOT NULL AND quantity_max IS NOT NULL)",
            name=op.f("ck_v2_listing_revision_quantity_range_pair"),
        ),
        sa.CheckConstraint(
            "base_quantity_max IS NULL OR base_quantity_max > 0",
            name=op.f("ck_v2_listing_revision_base_quantity_max"),
        ),
        sa.CheckConstraint(
            "base_quantity_min IS NULL OR base_quantity_max >= base_quantity_min",
            name=op.f("ck_v2_listing_revision_base_quantity_range_order"),
        ),
        sa.CheckConstraint(
            "base_quantity_min IS NULL OR base_quantity_min > 0",
            name=op.f("ck_v2_listing_revision_base_quantity_min"),
        ),
        sa.CheckConstraint(
            "base_quantity_value IS NULL OR "
            "(base_quantity_min IS NULL AND base_quantity_max IS NULL)",
            name=op.f("ck_v2_listing_revision_base_quantity_exact_or_range"),
        ),
        sa.CheckConstraint(
            "base_quantity_value IS NULL OR base_quantity_value > 0",
            name=op.f("ck_v2_listing_revision_base_quantity_value"),
        ),
        sa.CheckConstraint(
            "(base_quantity_value IS NULL AND base_quantity_min IS NULL "
            "AND base_quantity_max IS NULL AND base_unit IS NULL) OR "
            "((base_quantity_value IS NOT NULL OR base_quantity_min IS NOT NULL) "
            "AND base_unit IS NOT NULL)",
            name=op.f("ck_v2_listing_revision_base_unit_semantics"),
        ),
        sa.CheckConstraint(
            "last_observed_at >= first_observed_at",
            name=op.f("ck_v2_listing_revision_observation_range"),
        ),
        sa.CheckConstraint(
            "package_count IS NULL OR package_count > 0",
            name=op.f("ck_v2_listing_revision_package_count"),
        ),
        sa.CheckConstraint(
            "quantity_max IS NULL OR quantity_max > 0",
            name=op.f("ck_v2_listing_revision_quantity_max"),
        ),
        sa.CheckConstraint(
            "quantity_min IS NULL OR quantity_max >= quantity_min",
            name=op.f("ck_v2_listing_revision_quantity_range_order"),
        ),
        sa.CheckConstraint(
            "quantity_min IS NULL OR quantity_min > 0",
            name=op.f("ck_v2_listing_revision_quantity_min"),
        ),
        sa.CheckConstraint(
            "(quantity_value IS NULL AND quantity_min IS NULL AND quantity_max IS NULL "
            "AND quantity_unit IS NULL) OR "
            "((quantity_value IS NOT NULL OR quantity_min IS NOT NULL) "
            "AND quantity_unit IS NOT NULL)",
            name=op.f("ck_v2_listing_revision_quantity_unit_semantics"),
        ),
        sa.CheckConstraint(
            "quantity_value IS NULL OR (quantity_min IS NULL AND quantity_max IS NULL)",
            name=op.f("ck_v2_listing_revision_quantity_exact_or_range"),
        ),
        sa.CheckConstraint(
            "quantity_value IS NULL OR quantity_value > 0",
            name=op.f("ck_v2_listing_revision_quantity_value"),
        ),
        sa.ForeignKeyConstraint(
            ["first_crawl_record_id"],
            ["v2_crawl_record.id"],
            name=op.f("fk_v2_listing_revision_first_crawl_record_id_v2_crawl_record"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["v2_source_listing.id"],
            name=op.f("fk_v2_listing_revision_source_listing_id_v2_source_listing"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_listing_revision")),
        sa.UniqueConstraint(
            "source_listing_id", "identity_fingerprint", name="uq_v2_revision_listing_identity"
        ),
        sa.UniqueConstraint(
            "source_listing_id", "revision_no", name="uq_v2_revision_listing_number"
        ),
    )
    op.create_index(
        "ix_v2_revision_listing_observed",
        "v2_listing_revision",
        ["source_listing_id", "last_observed_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_v2_source_listing_current_revision",
        "v2_source_listing",
        "v2_listing_revision",
        ["current_revision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "v2_listing_match",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("listing_revision_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("item_variant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("match_status", sa.String(length=24), nullable=False),
        sa.Column("match_method", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("matched_fields", sa.JSON(), nullable=False),
        sa.Column("mismatch_fields", sa.JSON(), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("effective_from", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("effective_to", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_method IN ('GTIN','MODEL','RULE','MANUAL','ML')",
            name=op.f("ck_v2_listing_match_match_method"),
        ),
        sa.CheckConstraint(
            "match_status IN ('CANDIDATE','ACCEPTED','REJECTED','REVIEW_REQUIRED','SUPERSEDED')",
            name=op.f("ck_v2_listing_match_match_status"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_v2_listing_match_confidence")
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_v2_listing_match_effective_range"),
        ),
        sa.ForeignKeyConstraint(
            ["item_variant_id"],
            ["v2_item_variant.id"],
            name=op.f("fk_v2_listing_match_item_variant_id_v2_item_variant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_revision_id"],
            ["v2_listing_revision.id"],
            name=op.f("fk_v2_listing_match_listing_revision_id_v2_listing_revision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_listing_match")),
        sa.UniqueConstraint(
            "listing_revision_id",
            "item_variant_id",
            "matcher_version",
            name="uq_v2_match_revision_variant_version",
        ),
    )
    op.create_index(
        "ix_v2_match_revision_status_effective",
        "v2_listing_match",
        ["listing_revision_id", "match_status", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_v2_match_variant_status",
        "v2_listing_match",
        ["item_variant_id", "match_status"],
        unique=False,
    )
    op.create_table(
        "v2_price_observation",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("observation_key", sa.String(length=64), nullable=False),
        sa.Column("supersedes_observation_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("source_listing_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("listing_revision_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("crawl_record_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("region_scope", sa.String(length=24), nullable=False),
        sa.Column("region_code", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'CNY'"), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("original_price_type", sa.String(length=32), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("price_nature", sa.String(length=32), nullable=False),
        sa.Column("price_type", sa.String(length=32), nullable=False),
        sa.Column("pricing_basis", sa.String(length=24), nullable=False),
        sa.Column("promotion_label", sa.String(length=128), nullable=True),
        sa.Column("availability", sa.String(length=24), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("unit_price_unit", sa.String(length=16), nullable=True),
        sa.Column("fee_status", sa.String(length=32), nullable=False),
        sa.Column("quality_status", sa.String(length=24), nullable=False),
        sa.Column("rejection_code", sa.String(length=64), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("displayed_price_text", sa.String(length=255), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(original_price IS NULL AND original_price_type = 'NONE') OR "
            "(original_price IS NOT NULL AND original_price_type <> 'NONE')",
            name=op.f("ck_v2_price_observation_original_price_semantics"),
        ),
        sa.CheckConstraint(
            "(quality_status = 'ACCEPTED' AND rejection_code IS NULL) OR "
            "(quality_status <> 'ACCEPTED' AND rejection_code IS NOT NULL)",
            name=op.f("ck_v2_price_observation_quality_semantics"),
        ),
        sa.CheckConstraint(
            "quality_status <> 'ACCEPTED' OR "
            "(current_price IS NOT NULL AND region_scope <> 'UNKNOWN' "
            "AND price_nature <> 'UNKNOWN' "
            "AND pricing_basis IN ('PACKAGE_TOTAL','UNIT_QUOTED') "
            "AND (pricing_basis <> 'UNIT_QUOTED' OR unit_price IS NOT NULL) "
            "AND ((price_nature IN ('RETAIL_OFFER','WHOLESALE_OFFER') "
            "AND price_type = 'DIRECT_UNCONDITIONAL' "
            "AND fee_status IN ('ITEM_ONLY','SEPARATE_FEES_EXCLUDED')) "
            "OR (price_nature IN ('RETAIL_AVERAGE','WHOLESALE_AVERAGE','MARKET_AVERAGE') "
            "AND price_type = 'PUBLISHED_VALUE' "
            "AND fee_status = 'NOT_APPLICABLE')))",
            name=op.f("ck_v2_price_observation_accepted_eligibility"),
        ),
        sa.CheckConstraint(
            "availability IN "
            "('ON_SALE','OUT_OF_STOCK','RESERVATION','PRE_SALE','COMING_SOON',"
            "'OFF_SHELF','UNKNOWN')",
            name=op.f("ck_v2_price_observation_availability"),
        ),
        sa.CheckConstraint("currency = 'CNY'", name=op.f("ck_v2_price_observation_currency")),
        sa.CheckConstraint(
            "fee_status IN "
            "('ITEM_ONLY','SEPARATE_FEES_EXCLUDED','NOT_APPLICABLE','INSEPARABLE','UNKNOWN')",
            name=op.f("ck_v2_price_observation_fee_status"),
        ),
        sa.CheckConstraint(
            "original_price_type IN ('CROSSED_OUT','MSRP','EXPLICIT_ORIGINAL','NONE')",
            name=op.f("ck_v2_price_observation_original_price_type"),
        ),
        sa.CheckConstraint(
            "price_nature IN ('RETAIL_OFFER','WHOLESALE_OFFER','RETAIL_AVERAGE',"
            "'WHOLESALE_AVERAGE','MARKET_AVERAGE','UNKNOWN')",
            name=op.f("ck_v2_price_observation_price_nature"),
        ),
        sa.CheckConstraint(
            "price_type IN "
            "('DIRECT_UNCONDITIONAL','PUBLISHED_VALUE','MEMBER','COUPON','SUBSIDY',"
            "'STARTING','INSTALLMENT','DEPOSIT','BUNDLE','UNKNOWN')",
            name=op.f("ck_v2_price_observation_price_type"),
        ),
        sa.CheckConstraint(
            "pricing_basis IN ('PACKAGE_TOTAL','UNIT_QUOTED','VARIABLE_ESTIMATE','UNKNOWN')",
            name=op.f("ck_v2_price_observation_pricing_basis"),
        ),
        sa.CheckConstraint(
            "quality_status IN ('ACCEPTED','REVIEW_REQUIRED','REJECTED')",
            name=op.f("ck_v2_price_observation_quality_status"),
        ),
        sa.CheckConstraint(
            "region_scope <> 'MULTI'", name=op.f("ck_v2_price_observation_single_region")
        ),
        sa.CheckConstraint(
            "region_scope IN "
            "('NATIONAL','PROVINCE','CITY','DISTRICT','DELIVERY_ZONE','UNKNOWN','MULTI')",
            name=op.f("ck_v2_price_observation_region_scope"),
        ),
        sa.CheckConstraint(
            "region_scope <> 'NATIONAL' OR region_code = 'CN'",
            name=op.f("ck_v2_price_observation_national_region"),
        ),
        sa.CheckConstraint(
            "(unit_price IS NULL AND unit_price_unit IS NULL) OR "
            "(unit_price IS NOT NULL AND unit_price_unit IS NOT NULL)",
            name=op.f("ck_v2_price_observation_unit_price_semantics"),
        ),
        sa.CheckConstraint(
            "current_price IS NULL OR current_price > 0",
            name=op.f("ck_v2_price_observation_current_price"),
        ),
        sa.CheckConstraint(
            "original_price IS NULL OR original_price > 0",
            name=op.f("ck_v2_price_observation_original_price"),
        ),
        sa.CheckConstraint(
            "unit_price IS NULL OR unit_price > 0", name=op.f("ck_v2_price_observation_unit_price")
        ),
        sa.ForeignKeyConstraint(
            ["crawl_record_id"],
            ["v2_crawl_record.id"],
            name=op.f("fk_v2_price_observation_crawl_record_id_v2_crawl_record"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_revision_id"],
            ["v2_listing_revision.id"],
            name=op.f("fk_v2_price_observation_listing_revision_id_v2_listing_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["v2_source_listing.id"],
            name=op.f("fk_v2_price_observation_source_listing_id_v2_source_listing"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_observation_id"],
            ["v2_price_observation.id"],
            name="fk_v2_price_observation_supersedes",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_price_observation")),
        sa.UniqueConstraint(
            "observation_key", name=op.f("uq_v2_price_observation_observation_key")
        ),
    )
    op.create_index(
        "ix_v2_price_crawl_record", "v2_price_observation", ["crawl_record_id"], unique=False
    )
    op.create_index(
        "ix_v2_price_listing_region_observed",
        "v2_price_observation",
        ["source_listing_id", "region_scope", "region_code", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_price_observed_at", "v2_price_observation", ["observed_at"], unique=False
    )
    op.create_index(
        "ix_v2_price_quality_observed",
        "v2_price_observation",
        ["quality_status", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_price_revision_observed",
        "v2_price_observation",
        ["listing_revision_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_price_supersedes",
        "v2_price_observation",
        ["supersedes_observation_id"],
        unique=False,
    )
    op.create_table(
        "v2_price_current",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("source_listing_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("listing_revision_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("region_scope", sa.String(length=24), nullable=False),
        sa.Column("region_code", sa.String(length=32), nullable=False),
        sa.Column("price_observation_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "region_scope IN "
            "('NATIONAL','PROVINCE','CITY','DISTRICT','DELIVERY_ZONE','UNKNOWN','MULTI')",
            name=op.f("ck_v2_price_current_region_scope"),
        ),
        sa.CheckConstraint(
            "region_scope NOT IN ('UNKNOWN','MULTI')", name=op.f("ck_v2_price_current_known_region")
        ),
        sa.CheckConstraint(
            "region_scope <> 'NATIONAL' OR region_code = 'CN'",
            name=op.f("ck_v2_price_current_national_region"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_revision_id"],
            ["v2_listing_revision.id"],
            name=op.f("fk_v2_price_current_listing_revision_id_v2_listing_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["price_observation_id"],
            ["v2_price_observation.id"],
            name=op.f("fk_v2_price_current_price_observation_id_v2_price_observation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["v2_source_listing.id"],
            name=op.f("fk_v2_price_current_source_listing_id_v2_source_listing"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_v2_price_current")),
        sa.UniqueConstraint(
            "price_observation_id", name=op.f("uq_v2_price_current_price_observation_id")
        ),
        sa.UniqueConstraint(
            "source_listing_id", "region_scope", "region_code", name="uq_v2_current_listing_region"
        ),
    )
    op.create_index(
        "ix_v2_current_region_observed",
        "v2_price_current",
        ["region_scope", "region_code", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_v2_current_revision_region",
        "v2_price_current",
        ["listing_revision_id", "region_scope", "region_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping each table removes its own indexes. Explicit index drops can fail
    # on MySQL when InnoDB selected an index to support a foreign key.
    op.drop_table("v2_price_current")
    op.drop_table("v2_price_observation")
    op.drop_table("v2_listing_match")
    op.drop_constraint(
        "fk_v2_source_listing_current_revision",
        "v2_source_listing",
        type_="foreignkey",
    )
    op.drop_table("v2_listing_revision")
    op.drop_table("v2_crawl_record")
    op.drop_table("v2_source_listing")
    op.drop_table("v2_item_variant")
    op.drop_table("v2_merchant")
    op.drop_table("v2_crawl_run")
    op.drop_table("v2_catalog_item")
    op.drop_table("v2_source_channel")
    op.drop_table("v2_category")
    op.drop_table("v2_brand")
