"""initial schema

Revision ID: 874227e1c153
Revises:
Create Date: 2026-08-05 20:43:49.320674
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "874227e1c153"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_zh", sa.String(length=64), nullable=False),
        sa.Column("name_en", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand")),
        sa.UniqueConstraint("code", name=op.f("uq_brand_code")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_zh", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
            name=op.f("fk_category_parent_id_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("code", name=op.f("uq_category_code")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("official_product_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("series_name", sa.String(length=128), nullable=True),
        sa.Column("model_number", sa.String(length=128), nullable=True),
        sa.Column("official_url", sa.String(length=1024), nullable=False),
        sa.Column(
            "lifecycle_status",
            sa.String(length=32),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("first_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('ACTIVE','INACTIVE','UNKNOWN')",
            name=op.f("ck_product_lifecycle_status"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brand.id"], name=op.f("fk_product_brand_id_brand"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_product_category_id_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint(
            "brand_id", "official_product_id", name="uq_product_brand_official_product"
        ),
    )
    op.create_table(
        "sales_channel",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("allowed_domains", sa.JSON(), nullable=False),
        sa.Column(
            "region_code", sa.String(length=2), server_default=sa.text("'CN'"), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'CNY'"), nullable=False),
        sa.Column(
            "seller_type",
            sa.String(length=32),
            server_default=sa.text("'OFFICIAL_DIRECT'"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'CNY'", name=op.f("ck_sales_channel_currency")),
        sa.CheckConstraint("region_code = 'CN'", name=op.f("ck_sales_channel_region_code")),
        sa.CheckConstraint(
            "seller_type = 'OFFICIAL_DIRECT'", name=op.f("ck_sales_channel_seller_type")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
            name=op.f("fk_sales_channel_brand_id_brand"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_channel")),
        sa.UniqueConstraint("code", name=op.f("uq_sales_channel_code")),
    )
    op.create_table(
        "crawl_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("run_type", sa.String(length=32), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("adapter_version", sa.String(length=64), nullable=False),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("discovered_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("success_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_summary", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "run_type IN ('DISCOVERY','PRICE','FULL','REPLAY')", name=op.f("ck_crawl_run_run_type")
        ),
        sa.CheckConstraint(
            "status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED')",
            name=op.f("ck_crawl_run_status"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('SCHEDULED','MANUAL')", name=op.f("ck_crawl_run_trigger_type")
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["sales_channel.id"],
            name=op.f("fk_crawl_run_channel_id_sales_channel"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_run")),
    )
    op.create_table(
        "sku",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("official_sku_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=128), nullable=True),
        sa.Column("capacity", sa.String(length=64), nullable=True),
        sa.Column("memory", sa.String(length=64), nullable=True),
        sa.Column("connectivity", sa.String(length=64), nullable=True),
        sa.Column("size", sa.String(length=64), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("spec_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False
        ),
        sa.Column("first_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE','INACTIVE','UNKNOWN')", name=op.f("ck_sku_status")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_sku_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku")),
        sa.UniqueConstraint("product_id", "official_sku_id", name="uq_sku_product_official_sku"),
        sa.UniqueConstraint(
            "product_id", "spec_fingerprint", name="uq_sku_product_spec_fingerprint"
        ),
    )
    op.create_table(
        "crawl_record",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("crawl_run_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_key", sa.String(length=255), nullable=False),
        sa.Column("request_url", sa.String(length=1024), nullable=False),
        sa.Column("final_url", sa.String(length=1024), nullable=False),
        sa.Column("fetch_method", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("fetch_status", sa.String(length=32), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_hash", sa.String(length=64), nullable=True),
        sa.Column("raw_path", sa.String(length=1024), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("fetched_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["crawl_run.id"],
            name=op.f("fk_crawl_record_crawl_run_id_crawl_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_record")),
    )
    op.create_index(
        "ix_crawl_record_entity", "crawl_record", ["entity_type", "entity_key"], unique=False
    )
    op.create_index("ix_crawl_record_fetched_at", "crawl_record", ["fetched_at"], unique=False)
    op.create_index(
        "ix_crawl_record_run_parse_status",
        "crawl_record",
        ["crawl_run_id", "parse_status"],
        unique=False,
    )
    op.create_table(
        "official_offer",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sku_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("official_offer_id", sa.String(length=128), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column(
            "availability",
            sa.String(length=32),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("consecutive_misses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("first_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "availability IN "
            "('ON_SALE','OUT_OF_STOCK','RESERVATION','PRE_SALE','COMING_SOON',"
            "'OFF_SHELF','UNKNOWN')",
            name=op.f("ck_official_offer_availability"),
        ),
        sa.CheckConstraint(
            "consecutive_misses >= 0", name=op.f("ck_official_offer_consecutive_misses")
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["sales_channel.id"],
            name=op.f("fk_official_offer_channel_id_sales_channel"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name=op.f("fk_official_offer_sku_id_sku"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_official_offer")),
        sa.UniqueConstraint(
            "channel_id", "official_offer_id", name="uq_offer_channel_official_offer"
        ),
        sa.UniqueConstraint("sku_id", "channel_id", name="uq_offer_sku_channel"),
    )
    op.create_table(
        "price_current",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'CNY'"), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "original_price_type",
            sa.String(length=32),
            server_default=sa.text("'NONE'"),
            nullable=False,
        ),
        sa.Column("current_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("crawl_run_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(original_price IS NULL AND original_price_type = 'NONE') OR "
            "(original_price IS NOT NULL AND original_price_type <> 'NONE')",
            name=op.f("ck_price_current_original_price_semantics"),
        ),
        sa.CheckConstraint("currency = 'CNY'", name=op.f("ck_price_current_currency")),
        sa.CheckConstraint(
            "original_price_type IN ('CROSSED_OUT','MSRP','EXPLICIT_ORIGINAL','NONE')",
            name=op.f("ck_price_current_original_price_type"),
        ),
        sa.CheckConstraint(
            "current_price IS NULL OR current_price > 0",
            name=op.f("ck_price_current_current_price"),
        ),
        sa.CheckConstraint(
            "original_price IS NULL OR original_price > 0",
            name=op.f("ck_price_current_original_price"),
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["crawl_run.id"],
            name=op.f("fk_price_current_crawl_run_id_crawl_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["official_offer.id"],
            name=op.f("fk_price_current_offer_id_official_offer"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_current")),
        sa.UniqueConstraint("offer_id", name=op.f("uq_price_current_offer_id")),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'CNY'"), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("original_price_type", sa.String(length=32), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("valid_from", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("last_observed_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("valid_to", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("crawl_run_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(original_price IS NULL AND original_price_type = 'NONE') OR "
            "(original_price IS NOT NULL AND original_price_type <> 'NONE')",
            name=op.f("ck_price_history_original_price_semantics"),
        ),
        sa.CheckConstraint("currency = 'CNY'", name=op.f("ck_price_history_currency")),
        sa.CheckConstraint(
            "original_price_type IN ('CROSSED_OUT','MSRP','EXPLICIT_ORIGINAL','NONE')",
            name=op.f("ck_price_history_original_price_type"),
        ),
        sa.CheckConstraint(
            "current_price IS NULL OR current_price > 0",
            name=op.f("ck_price_history_current_price"),
        ),
        sa.CheckConstraint(
            "last_observed_at >= valid_from", name=op.f("ck_price_history_last_observed_at")
        ),
        sa.CheckConstraint(
            "original_price IS NULL OR original_price > 0",
            name=op.f("ck_price_history_original_price"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_price_history_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["crawl_run.id"],
            name=op.f("fk_price_history_crawl_run_id_crawl_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["official_offer.id"],
            name=op.f("fk_price_history_offer_id_official_offer"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
    )
    op.create_index(
        "ix_price_history_offer_valid_from",
        "price_history",
        ["offer_id", "valid_from"],
        unique=False,
    )
    op.create_index(
        "ix_price_history_offer_valid_to", "price_history", ["offer_id", "valid_to"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Indexes are dropped with their tables. Dropping them first is invalid on
    # MySQL when InnoDB uses an index to satisfy a foreign-key requirement.
    op.drop_table("price_history")
    op.drop_table("price_current")
    op.drop_table("official_offer")
    op.drop_table("crawl_record")
    op.drop_table("sku")
    op.drop_table("crawl_run")
    op.drop_table("sales_channel")
    op.drop_table("product")
    op.drop_table("category")
    op.drop_table("brand")
